---
# Go-Waku
go_waku_libp2p_port: 30303
go_waku_metrics_port: 8008

# Firewall
open_ports_default_comment: '{{ go_waku_service_name }}'
open_ports_default_chain: 'SERVICES'
open_ports_list:
  - { port: '{{ go_waku_libp2p_port }}' }
  - { port: '{{ go_waku_metrics_port }}', chain: 'VPN', ipset: 'metrics.hq' }
