---
# LetsEncrypt via Certbot
certbot_admin_email: 'devops@status.im'
certbot_docker_enabled: true
certbot_containers_to_stop: ['{{ go_waku_cont_name }}']
certbot_services_to_stop: []
certbot_certs:
  - domains: [ '{{ dns_entry }}' ]

# Go-Waku
go_waku_service_name: 'go-waku'
go_waku_cont_name: '{{ go_waku_service_name }}'
go_waku_cont_tag: 'deploy-{{ stage }}'
# DiscV5
go_waku_disc_v5_enabled: true
# DNSDiscovery
go_waku_dns_disc_enabled: true
go_waku_dns_disc_url: 'enrtree://AOGECG2SPND25EEFMAJ5WF3KSGJNSGV356DSTL2YVLLZWIV6SAYBM@{{ stage }}.nodes.status.im'
# Ports
go_waku_rpc_port: 8545
go_waku_libp2p_port: 30303
go_waku_metrics_port: 8008
go_waku_disc_v5_port: 9000
# Protocols
go_waku_store_enabled: true
go_waku_relay_enabled: true
go_waku_filter_enabled: true
go_waku_lightpush_enabled: true
# Secure Websocket
go_waku_websocket_enabled: false
go_waku_websocket_port: 9001
go_waku_websocket_secure_enabled: true
go_waku_websocket_secure_port: 443
go_waku_websocket_ssl_dir: '/etc/letsencrypt'
go_waku_websocket_ssl_cert: '/etc/letsencrypt/live/{{ dns_entry }}/fullchain.pem'
go_waku_websocket_ssl_key: '/etc/letsencrypt/live/{{ dns_entry }}/privkey.pem'

# SQLite store
go_waku_store_duration: '168h' # 7 days
go_waku_store_capacity: '{{ 0 if stage == "prod" else 1000000 }}' # 0 is unlimited
go_waku_store_vacuum: true

# Resource Scaling
go_waku_resource_scaling_memory_percentage: 50
go_waku_resource_scaling_fd_percentage: 50

# Firewall
open_ports_default_comment: '{{ go_waku_service_name }}'
open_ports_default_chain: 'SERVICES'
open_ports_list:
  - { port: 80, comment: 'Certbot' }
  - { port: '{{ go_waku_websocket_secure_port }}' }
  - { port: '{{ go_waku_libp2p_port }}' }
  - { port: '{{ go_waku_metrics_port }}', chain: 'VPN', ipset: 'metrics.hq' }
  - { port: '{{ go_waku_disc_v5_port }}', protocol: 'udp' }
