---
# LetsEncrypt via Certbot
certbot_admin_email: 'devops@status.im'
certbot_certs:
  - domains: [ '{{ dns_entry }}' ]

# Go-Waku
go_waku_libp2p_port: 30303
go_waku_metrics_port: 8008
go_waku_websocket_port: 9001
# Protocols
go_waku_websocket_enabled: true
go_waku_rendezvous_server_enabled: true
# SSL proxy
go_waku_websocket_ssl_proxy_enabled: true
go_waku_websocket_ssl_domain: '{{ dns_entry }}'
go_waku_websocket_ssl_cert: '/etc/letsencrypt/live/{{ dns_entry }}/fullchain.pem'
go_waku_websocket_ssl_key: '/etc/letsencrypt/live/{{ dns_entry }}/privkey.pem'

# Firewall
open_ports_default_comment: '{{ go_waku_service_name }}'
open_ports_default_chain: 'SERVICES'
open_ports_list:
  - { port: 80, comment: '{{ go_waku_service_name }} Websocket Proxy' }
  - { port: 443, comment: '{{ go_waku_service_name }} Websocket Proxy' }
  - { port: '{{ go_waku_libp2p_port }}' }
  - { port: '{{ go_waku_metrics_port }}', chain: 'VPN', ipset: 'metrics.hq' }
