---
- name: Verify Ansible versions
  hosts: all
  tags: always
  become: false
  run_once: true
  gather_facts: false
  tasks:
    - local_action: command ./versioncheck.py
      changed_when: false

- name: Configure Waku Nodes
  hosts:
    - go-waku-test
  roles:
    - { role: swap-file,  tags: swap-file }
