---
- name: open-ports
  src: git@github.com:status-im/infra-role-open-ports.git
  version: 24dc30dbdf85e6758cb6924074b2f7a0f4541524
  scm: git

- name: swap-file
  src: git@github.com:status-im/infra-role-swap-file.git
  version: 7b63fb7b5f0c525aa191e1a410fd79f7eab8d11a
  scm: git

- name: infra-role-bootstrap-linux
  src: git@github.com:status-im/infra-role-bootstrap-linux.git
  version: 3b61bca714677e6a2a44a7500659b16b78977181
  scm: git

- name: infra-role-wireguard
  src: git@github.com:status-im/infra-role-wireguard.git
  version: 345c9dd85ff8e57bce7e492dc05d685aee1f076c
  scm: git

- name: consul-service
  src: git@github.com:status-im/infra-role-consul-service.git
  version: 61a248a697d37c98b575be942bb6e86deb512380
  scm: git

- name: certbot
  src: git@github.com:status-im/infra-role-certbot.git
  version: 4b93ca81043f843d573c43b42f50e7620e81590d
  scm: git
