---
- name: Get data centers
  uri:
    url: '{{ consul_url }}/datacenters'
  run_once: true
  register: data_centers

- name: Discover other fleet peers
  uri:
    url: '{{ consul_url }}/service/{{ go_waku_service_name }}?dc={{ item }}&filter=NodeMeta.stage=={{ stage }}'
  run_once: true
  with_items: '{{ data_centers.json }}'
  register: go_waku_services

- name: Discover nim-waku fleet peers
  uri:
    url: '{{ consul_url }}/service/nim-waku-v2?dc={{ item }}&filter=NodeMeta.stage=={{ stage }}'
  run_once: true
  with_items: '{{ data_centers.json }}'
  register: nim_waku_services

- name: Combine data centers into one list
  set_fact:
    go_waku_peers: '{{ go_waku_services.results | sum(attribute="json", start=[]) }}'
    nim_waku_peers: '{{ nim_waku_services.results | sum(attribute="json", start=[]) }}'

- name: Extract fleet stages from services
  set_fact:
    go_waku_static_nodes: |
      {{ (go_waku_peers + nim_waku_peers)
      | map(attribute="ServiceMeta.node_enode")
      | list }}
