---
- name: Configure Nginx proxy for Websocket port
  include_role:
    name: nginx
  vars:
    nginx_sites:
      go_waku_websocket_http:
        - listen 80
        - server_name {{ go_waku_websocket_ssl_domain }}
        - return 302 https://$host$request_uri

      go_waku_websocket_ssl:
        - listen 443 ssl
        - server_name {{ go_waku_websocket_ssl_domain }}
        - ssl_certificate     {{ go_waku_websocket_ssl_cert }}
        - ssl_certificate_key {{ go_waku_websocket_ssl_key }}
        - location / {
            proxy_pass http://localhost:{{ go_waku_websocket_port }}/;
          }
